services:
  - type: web
    name: simulador-cuantico
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn webapp:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: FLASK_ENV
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: RENDER
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: simulador-db
          property: connectionString
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: simulador-db
    databaseName: simulador
    plan: free